//! Formatting functions for camera property values
//!
//! This module provides human-readable display formatting for raw SDK property values.
//! Most formatting is now handled by the types in [`crate::property::types`] which implement
//! the [`Display`](std::fmt::Display) trait. This module is kept for backwards compatibility.

use crate::property::DriveMode;

impl std::fmt::Display for DriveMode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            Self::Single => "Single",
            Self::ContinuousHi => "Cont. Hi",
            Self::ContinuousHiPlus => "Cont. Hi+",
            Self::ContinuousHiLive => "Cont. Hi Live",
            Self::ContinuousLo => "Cont. Lo",
            Self::Continuous => "Continuous",
            Self::ContinuousSpeedPriority => "Cont. Speed",
            Self::ContinuousMid => "Cont. Mid",
            Self::ContinuousMidLive => "Cont. Mid Live",
            Self::ContinuousLoLive => "Cont. Lo Live",
            Self::SingleBurstShootingLo => "Burst Lo",
            Self::SingleBurstShootingMid => "Burst Mid",
            Self::SingleBurstShootingHi => "Burst Hi",
            Self::FocusBracket => "Focus Bracket",
            Self::Timelapse => "Timelapse",
            Self::Timer2s => "Timer 2s",
            Self::Timer5s => "Timer 5s",
            Self::Timer10s => "Timer 10s",

            // Continuous brackets
            Self::ContinuousBracket03Ev3Pics => "C.BRK 0.3EV 3",
            Self::ContinuousBracket03Ev5Pics => "C.BRK 0.3EV 5",
            Self::ContinuousBracket03Ev9Pics => "C.BRK 0.3EV 9",
            Self::ContinuousBracket03Ev2PicsPlus => "C.BRK 0.3EV 2+",
            Self::ContinuousBracket03Ev2PicsMinus => "C.BRK 0.3EV 2-",
            Self::ContinuousBracket03Ev7Pics => "C.BRK 0.3EV 7",
            Self::ContinuousBracket05Ev3Pics => "C.BRK 0.5EV 3",
            Self::ContinuousBracket05Ev5Pics => "C.BRK 0.5EV 5",
            Self::ContinuousBracket05Ev9Pics => "C.BRK 0.5EV 9",
            Self::ContinuousBracket05Ev2PicsPlus => "C.BRK 0.5EV 2+",
            Self::ContinuousBracket05Ev2PicsMinus => "C.BRK 0.5EV 2-",
            Self::ContinuousBracket05Ev7Pics => "C.BRK 0.5EV 7",
            Self::ContinuousBracket07Ev3Pics => "C.BRK 0.7EV 3",
            Self::ContinuousBracket07Ev5Pics => "C.BRK 0.7EV 5",
            Self::ContinuousBracket07Ev9Pics => "C.BRK 0.7EV 9",
            Self::ContinuousBracket07Ev2PicsPlus => "C.BRK 0.7EV 2+",
            Self::ContinuousBracket07Ev2PicsMinus => "C.BRK 0.7EV 2-",
            Self::ContinuousBracket07Ev7Pics => "C.BRK 0.7EV 7",
            Self::ContinuousBracket10Ev3Pics => "C.BRK 1.0EV 3",
            Self::ContinuousBracket10Ev5Pics => "C.BRK 1.0EV 5",
            Self::ContinuousBracket10Ev9Pics => "C.BRK 1.0EV 9",
            Self::ContinuousBracket10Ev2PicsPlus => "C.BRK 1.0EV 2+",
            Self::ContinuousBracket10Ev2PicsMinus => "C.BRK 1.0EV 2-",
            Self::ContinuousBracket10Ev7Pics => "C.BRK 1.0EV 7",
            Self::ContinuousBracket13Ev2PicsPlus => "C.BRK 1.3EV 2+",
            Self::ContinuousBracket13Ev2PicsMinus => "C.BRK 1.3EV 2-",
            Self::ContinuousBracket13Ev3Pics => "C.BRK 1.3EV 3",
            Self::ContinuousBracket13Ev5Pics => "C.BRK 1.3EV 5",
            Self::ContinuousBracket13Ev7Pics => "C.BRK 1.3EV 7",
            Self::ContinuousBracket15Ev2PicsPlus => "C.BRK 1.5EV 2+",
            Self::ContinuousBracket15Ev2PicsMinus => "C.BRK 1.5EV 2-",
            Self::ContinuousBracket15Ev3Pics => "C.BRK 1.5EV 3",
            Self::ContinuousBracket15Ev5Pics => "C.BRK 1.5EV 5",
            Self::ContinuousBracket15Ev7Pics => "C.BRK 1.5EV 7",
            Self::ContinuousBracket17Ev2PicsPlus => "C.BRK 1.7EV 2+",
            Self::ContinuousBracket17Ev2PicsMinus => "C.BRK 1.7EV 2-",
            Self::ContinuousBracket17Ev3Pics => "C.BRK 1.7EV 3",
            Self::ContinuousBracket17Ev5Pics => "C.BRK 1.7EV 5",
            Self::ContinuousBracket17Ev7Pics => "C.BRK 1.7EV 7",
            Self::ContinuousBracket20Ev3Pics => "C.BRK 2.0EV 3",
            Self::ContinuousBracket20Ev5Pics => "C.BRK 2.0EV 5",
            Self::ContinuousBracket20Ev2PicsPlus => "C.BRK 2.0EV 2+",
            Self::ContinuousBracket20Ev2PicsMinus => "C.BRK 2.0EV 2-",
            Self::ContinuousBracket20Ev7Pics => "C.BRK 2.0EV 7",
            Self::ContinuousBracket23Ev2PicsPlus => "C.BRK 2.3EV 2+",
            Self::ContinuousBracket23Ev2PicsMinus => "C.BRK 2.3EV 2-",
            Self::ContinuousBracket23Ev3Pics => "C.BRK 2.3EV 3",
            Self::ContinuousBracket23Ev5Pics => "C.BRK 2.3EV 5",
            Self::ContinuousBracket25Ev2PicsPlus => "C.BRK 2.5EV 2+",
            Self::ContinuousBracket25Ev2PicsMinus => "C.BRK 2.5EV 2-",
            Self::ContinuousBracket25Ev3Pics => "C.BRK 2.5EV 3",
            Self::ContinuousBracket25Ev5Pics => "C.BRK 2.5EV 5",
            Self::ContinuousBracket27Ev2PicsPlus => "C.BRK 2.7EV 2+",
            Self::ContinuousBracket27Ev2PicsMinus => "C.BRK 2.7EV 2-",
            Self::ContinuousBracket27Ev3Pics => "C.BRK 2.7EV 3",
            Self::ContinuousBracket27Ev5Pics => "C.BRK 2.7EV 5",
            Self::ContinuousBracket30Ev3Pics => "C.BRK 3.0EV 3",
            Self::ContinuousBracket30Ev5Pics => "C.BRK 3.0EV 5",
            Self::ContinuousBracket30Ev2PicsPlus => "C.BRK 3.0EV 2+",
            Self::ContinuousBracket30Ev2PicsMinus => "C.BRK 3.0EV 2-",

            // Single brackets
            Self::SingleBracket03Ev3Pics => "S.BRK 0.3EV 3",
            Self::SingleBracket03Ev5Pics => "S.BRK 0.3EV 5",
            Self::SingleBracket03Ev9Pics => "S.BRK 0.3EV 9",
            Self::SingleBracket03Ev2PicsPlus => "S.BRK 0.3EV 2+",
            Self::SingleBracket03Ev2PicsMinus => "S.BRK 0.3EV 2-",
            Self::SingleBracket03Ev7Pics => "S.BRK 0.3EV 7",
            Self::SingleBracket05Ev3Pics => "S.BRK 0.5EV 3",
            Self::SingleBracket05Ev5Pics => "S.BRK 0.5EV 5",
            Self::SingleBracket05Ev9Pics => "S.BRK 0.5EV 9",
            Self::SingleBracket05Ev2PicsPlus => "S.BRK 0.5EV 2+",
            Self::SingleBracket05Ev2PicsMinus => "S.BRK 0.5EV 2-",
            Self::SingleBracket05Ev7Pics => "S.BRK 0.5EV 7",
            Self::SingleBracket07Ev3Pics => "S.BRK 0.7EV 3",
            Self::SingleBracket07Ev5Pics => "S.BRK 0.7EV 5",
            Self::SingleBracket07Ev9Pics => "S.BRK 0.7EV 9",
            Self::SingleBracket07Ev2PicsPlus => "S.BRK 0.7EV 2+",
            Self::SingleBracket07Ev2PicsMinus => "S.BRK 0.7EV 2-",
            Self::SingleBracket07Ev7Pics => "S.BRK 0.7EV 7",
            Self::SingleBracket10Ev3Pics => "S.BRK 1.0EV 3",
            Self::SingleBracket10Ev5Pics => "S.BRK 1.0EV 5",
            Self::SingleBracket10Ev9Pics => "S.BRK 1.0EV 9",
            Self::SingleBracket10Ev2PicsPlus => "S.BRK 1.0EV 2+",
            Self::SingleBracket10Ev2PicsMinus => "S.BRK 1.0EV 2-",
            Self::SingleBracket10Ev7Pics => "S.BRK 1.0EV 7",
            Self::SingleBracket13Ev2PicsPlus => "S.BRK 1.3EV 2+",
            Self::SingleBracket13Ev2PicsMinus => "S.BRK 1.3EV 2-",
            Self::SingleBracket13Ev3Pics => "S.BRK 1.3EV 3",
            Self::SingleBracket13Ev5Pics => "S.BRK 1.3EV 5",
            Self::SingleBracket13Ev7Pics => "S.BRK 1.3EV 7",
            Self::SingleBracket15Ev2PicsPlus => "S.BRK 1.5EV 2+",
            Self::SingleBracket15Ev2PicsMinus => "S.BRK 1.5EV 2-",
            Self::SingleBracket15Ev3Pics => "S.BRK 1.5EV 3",
            Self::SingleBracket15Ev5Pics => "S.BRK 1.5EV 5",
            Self::SingleBracket15Ev7Pics => "S.BRK 1.5EV 7",
            Self::SingleBracket17Ev2PicsPlus => "S.BRK 1.7EV 2+",
            Self::SingleBracket17Ev2PicsMinus => "S.BRK 1.7EV 2-",
            Self::SingleBracket17Ev3Pics => "S.BRK 1.7EV 3",
            Self::SingleBracket17Ev5Pics => "S.BRK 1.7EV 5",
            Self::SingleBracket17Ev7Pics => "S.BRK 1.7EV 7",
            Self::SingleBracket20Ev3Pics => "S.BRK 2.0EV 3",
            Self::SingleBracket20Ev5Pics => "S.BRK 2.0EV 5",
            Self::SingleBracket20Ev2PicsPlus => "S.BRK 2.0EV 2+",
            Self::SingleBracket20Ev2PicsMinus => "S.BRK 2.0EV 2-",
            Self::SingleBracket20Ev7Pics => "S.BRK 2.0EV 7",
            Self::SingleBracket23Ev2PicsPlus => "S.BRK 2.3EV 2+",
            Self::SingleBracket23Ev2PicsMinus => "S.BRK 2.3EV 2-",
            Self::SingleBracket23Ev3Pics => "S.BRK 2.3EV 3",
            Self::SingleBracket23Ev5Pics => "S.BRK 2.3EV 5",
            Self::SingleBracket25Ev2PicsPlus => "S.BRK 2.5EV 2+",
            Self::SingleBracket25Ev2PicsMinus => "S.BRK 2.5EV 2-",
            Self::SingleBracket25Ev3Pics => "S.BRK 2.5EV 3",
            Self::SingleBracket25Ev5Pics => "S.BRK 2.5EV 5",
            Self::SingleBracket27Ev2PicsPlus => "S.BRK 2.7EV 2+",
            Self::SingleBracket27Ev2PicsMinus => "S.BRK 2.7EV 2-",
            Self::SingleBracket27Ev3Pics => "S.BRK 2.7EV 3",
            Self::SingleBracket27Ev5Pics => "S.BRK 2.7EV 5",
            Self::SingleBracket30Ev3Pics => "S.BRK 3.0EV 3",
            Self::SingleBracket30Ev5Pics => "S.BRK 3.0EV 5",
            Self::SingleBracket30Ev2PicsPlus => "S.BRK 3.0EV 2+",
            Self::SingleBracket30Ev2PicsMinus => "S.BRK 3.0EV 2-",

            // Other modes
            Self::WbBracketLo => "WB BRK Lo",
            Self::WbBracketHi => "WB BRK Hi",
            Self::DroBracketLo => "DRO BRK Lo",
            Self::DroBracketHi => "DRO BRK Hi",
            Self::ContinuousTimer3Pics => "Cont. Timer 3",
            Self::ContinuousTimer5Pics => "Cont. Timer 5",
            Self::ContinuousTimer2s3Pics => "Timer 2s 3pics",
            Self::ContinuousTimer2s5Pics => "Timer 2s 5pics",
            Self::ContinuousTimer5s3Pics => "Timer 5s 3pics",
            Self::ContinuousTimer5s5Pics => "Timer 5s 5pics",
            Self::LpfBracket => "LPF Bracket",
            Self::RemoteCommander => "Remote",
            Self::MirrorUp => "Mirror Up",
            Self::SelfPortrait1 => "Self Portrait 1",
            Self::SelfPortrait2 => "Self Portrait 2",
        };
        write!(f, "{}", s)
    }
}
