//! Human-readable display names for camera properties.
//!
//! This module provides curated, user-friendly names for SDK properties.
//! Names are designed for UI display with proper capitalization, spacing, and abbreviations.

use crsdk_sys::DevicePropertyCode;

/// Get a human-readable display name for a property code.
///
/// Returns a curated display name for known properties, or falls back to
/// the basic SDK name for properties without custom names.
pub fn property_display_name(code: DevicePropertyCode) -> &'static str {
    match code {
        // === Exposure ===
        DevicePropertyCode::FNumber => "Aperture (f-number)",
        DevicePropertyCode::ShutterSpeed => "Shutter Speed",
        DevicePropertyCode::IsoSensitivity => "ISO",
        DevicePropertyCode::ExposureBiasCompensation => "Exposure Comp",
        DevicePropertyCode::ExposureProgramMode => "Exposure Mode",
        DevicePropertyCode::ExposureIndex => "Exposure Index (EI)",
        DevicePropertyCode::ExposureCtrlType => "Exposure Control Type",
        DevicePropertyCode::ExposureStep => "Exposure Step",
        DevicePropertyCode::AutoSlowShutter => "Auto Slow Shutter",
        DevicePropertyCode::ShutterModeSetting => "Shutter Control",
        DevicePropertyCode::ShutterModeStatus => "Shutter Mode",
        DevicePropertyCode::ShutterMode => "Shutter Unit",
        DevicePropertyCode::ShutterAngle => "Shutter Angle",
        DevicePropertyCode::ShutterSetting => "Shutter",
        DevicePropertyCode::ShutterSlow => "Slow Shutter",
        DevicePropertyCode::ShutterSlowFrames => "Slow Shutter Frames",
        DevicePropertyCode::ShutterECSSetting => "ECS Mode",
        DevicePropertyCode::ShutterECSFrequency => "ECS Frequency",
        DevicePropertyCode::ShutterECSNumber => "ECS Number",
        DevicePropertyCode::ShutterECSNumberStep => "ECS Step",
        DevicePropertyCode::GainControlSetting => "Gain Control",
        DevicePropertyCode::GainBaseIsoSensitivity => "Base ISO",
        DevicePropertyCode::GainBaseSensitivity => "Base Sensitivity",
        DevicePropertyCode::GainUnitSetting => "Gain Unit",
        DevicePropertyCode::GaindBCurrentValue => "Gain (dB)",
        DevicePropertyCode::GaindBValue => "Gain Value (dB)",
        DevicePropertyCode::IrisModeSetting => "Iris Mode",
        DevicePropertyCode::IrisDisplayUnit => "Iris Display Unit",
        DevicePropertyCode::IrisCloseSetting => "Iris Close Enable",
        DevicePropertyCode::BaseISOSwitchEI => "Base ISO (EI)",
        DevicePropertyCode::DRO => "D-Range Optimizer",
        DevicePropertyCode::MeteringMode => "Metering Mode",
        DevicePropertyCode::MeteredManualLevel => "Metered Manual Level",

        // === Focus ===
        DevicePropertyCode::FocusMode => "Focus Mode",
        DevicePropertyCode::FocusModeStatus => "Focus Mode Status",
        DevicePropertyCode::FocusModeSetting => "Focus Mode Setting",
        DevicePropertyCode::FocusArea => "Focus Area",
        DevicePropertyCode::AFTrackingSensitivity => "AF Tracking Sensitivity",
        DevicePropertyCode::AFAreaPosition => "AF Area Position",
        DevicePropertyCode::FocusMagnifierSetting => "Focus Magnifier",
        DevicePropertyCode::NearFar => "Near/Far Adjust",
        DevicePropertyCode::AFAssist => "AF Assist",
        DevicePropertyCode::AFIlluminator => "AF Illuminator",
        DevicePropertyCode::AFWithShutter => "AF with Shutter",
        DevicePropertyCode::PreAF => "Pre-AF",
        DevicePropertyCode::FocusOperation => "Focus Operation",
        DevicePropertyCode::FocusDrivingStatus => "Focus Driving Status",
        DevicePropertyCode::FocusIndication => "Focus Indication",
        DevicePropertyCode::FocusPositionSetting => "Focus Position",
        DevicePropertyCode::FocusPositionCurrentValue => "Focus Position (Current)",
        DevicePropertyCode::AFTransitionSpeed => "AF Transition Speed",
        DevicePropertyCode::AFSubjShiftSens => "AF Subject Shift Sensitivity",
        DevicePropertyCode::AFTrackForSpeedChange => "AF Track Speed Change",
        DevicePropertyCode::PrioritySetInAFS => "Priority in AF-S",
        DevicePropertyCode::PrioritySetInAFC => "Priority in AF-C",
        DevicePropertyCode::PushAutoFocus => "Push Auto Focus",
        DevicePropertyCode::AutoFocusHold => "AF Hold",
        DevicePropertyCode::FocusBracketShotNumber => "Focus Bracket Shots",
        DevicePropertyCode::FocusBracketFocusRange => "Focus Bracket Range",
        DevicePropertyCode::SubjectRecognitionInAF => "Subject Recognition",
        DevicePropertyCode::FaceEyeDetectionAFStatus => "Face/Eye Detection Status",
        DevicePropertyCode::FaceEyeFrameDisplay => "Face/Eye Frame Display",

        // === White Balance ===
        DevicePropertyCode::WhiteBalance => "White Balance",
        DevicePropertyCode::WhiteBalanceModeSetting => "WB Mode",
        DevicePropertyCode::Colortemp => "Color Temperature",
        DevicePropertyCode::ColortempStep => "Color Temp Step",
        DevicePropertyCode::ColorTuningAB => "WB Shift A-B",
        DevicePropertyCode::ColorTuningGM => "WB Shift G-M",
        DevicePropertyCode::WhiteBalanceSwitch => "WB Switch",
        DevicePropertyCode::WhiteBalanceOffsetSetting => "WB Offset",
        DevicePropertyCode::WhiteBalanceOffsetColorTemp => "WB Offset (Color Temp)",
        DevicePropertyCode::WhiteBalanceTint => "WB Tint",
        DevicePropertyCode::WhiteBalanceTintStep => "WB Tint Step",
        DevicePropertyCode::WhiteBalanceRGain => "WB R Gain",
        DevicePropertyCode::WhiteBalanceBGain => "WB B Gain",
        DevicePropertyCode::WhiteBalancePresetColorTemperature => "WB Preset Color Temp",
        DevicePropertyCode::AWBL => "AWB Lock",
        DevicePropertyCode::AWB => "Auto White Balance",
        DevicePropertyCode::PrioritySetInAWB => "Priority in AWB",
        DevicePropertyCode::CustomWBCapture => "Custom WB Capture",
        DevicePropertyCode::CustomWBCaptureOperation => "Custom WB Operation",
        DevicePropertyCode::CustomWBExecutionState => "Custom WB Status",

        // === Image Quality ===
        DevicePropertyCode::FileType => "File Type",
        DevicePropertyCode::StillImageQuality => "JPEG Quality",
        DevicePropertyCode::ImageSize => "Image Size",
        DevicePropertyCode::AspectRatio => "Aspect Ratio",
        DevicePropertyCode::StillImageStoreDestination => "Save Destination",
        DevicePropertyCode::RAWFileCompressionType => "RAW Compression",
        DevicePropertyCode::CompressionFileFormatStill => "Compression Format",
        DevicePropertyCode::HighIsoNR => "High ISO Noise Reduction",
        DevicePropertyCode::LongExposureNR => "Long Exposure NR",
        DevicePropertyCode::HLGStillImage => "HLG Still Image",
        DevicePropertyCode::PictureEffect => "Picture Effect",
        DevicePropertyCode::SoftSkinEffect => "Soft Skin Effect",

        // === Movie ===
        DevicePropertyCode::MovieFileFormat => "Movie Format",
        DevicePropertyCode::MovieRecordingSetting => "Movie Quality",
        DevicePropertyCode::MovieRecordingFrameRateSetting => "Movie Frame Rate",
        DevicePropertyCode::MovieRecordingResolutionForMain => "Movie Resolution",
        DevicePropertyCode::MovieRecordingResolutionForProxy => "Proxy Resolution",
        DevicePropertyCode::MovieShootingMode => "Movie Shooting Mode",
        DevicePropertyCode::MovieShootingModeColorGamut => "Movie Color Gamut",
        DevicePropertyCode::RecordingState => "Recording State",
        DevicePropertyCode::RecordingMedia => "Recording Media",
        DevicePropertyCode::ProxyRecordingSetting => "Proxy Recording",
        DevicePropertyCode::RecordingSettingFileName => "Recording File Name",
        DevicePropertyCode::MovieRecordingMedia => "Movie Recording Media",
        DevicePropertyCode::TimeCodeFormat => "Timecode Format",
        DevicePropertyCode::TimeCodeMake => "Timecode Make",
        DevicePropertyCode::TimeCodePreset => "Timecode Preset",
        DevicePropertyCode::TimeCodeRun => "Timecode Run",
        DevicePropertyCode::RecorderMainStatus => "Recorder Status",
        DevicePropertyCode::RecorderProxyStatus => "Proxy Recorder Status",
        DevicePropertyCode::RecorderStartMain => "Start Recording",
        DevicePropertyCode::RecorderStartProxy => "Start Proxy Recording",
        DevicePropertyCode::SQModeSetting => "S&Q Mode",
        DevicePropertyCode::SQRecordingSetting => "S&Q Recording",
        DevicePropertyCode::SQRecordingFrameRateSetting => "S&Q Frame Rate",
        DevicePropertyCode::SQFrameRate => "S&Q Playback Rate",
        DevicePropertyCode::LogShootingMode => "Log Shooting Mode",
        DevicePropertyCode::LogShootingModeColorGamut => "Log Color Gamut",

        // === Drive Mode ===
        DevicePropertyCode::DriveMode => "Drive Mode",
        DevicePropertyCode::BracketOrder => "Bracket Order",
        DevicePropertyCode::RecordingSelfTimer => "Self Timer",
        DevicePropertyCode::RecordingSelfTimerCountTime => "Self Timer Duration",
        DevicePropertyCode::RecordingSelfTimerStatus => "Self Timer Status",
        DevicePropertyCode::IntervalRecNumberOfShots => "Interval Shots",
        DevicePropertyCode::IntervalRecShootingInterval => "Interval Time",
        DevicePropertyCode::IntervalRecStatus => "Interval Status",
        DevicePropertyCode::IntervalRecMode => "Interval Mode",
        DevicePropertyCode::IntervalRecShutterType => "Interval Shutter Type",
        DevicePropertyCode::ContinuousShootingSpotBoostStatus => "Burst Boost Status",
        DevicePropertyCode::ContinuousShootingSpotBoostFrameSpeed => "Burst Boost Speed",

        // === Media ===
        DevicePropertyCode::MediaSLOT1Status => "Slot 1 Status",
        DevicePropertyCode::MediaSLOT2Status => "Slot 2 Status",
        DevicePropertyCode::MediaSLOT3Status => "Slot 3 Status",
        DevicePropertyCode::MediaSLOT1RemainingNumber => "Slot 1 Remaining",
        DevicePropertyCode::MediaSLOT2RemainingNumber => "Slot 2 Remaining",
        DevicePropertyCode::MediaSLOT1RemainingTime => "Slot 1 Time Left",
        DevicePropertyCode::MediaSLOT2RemainingTime => "Slot 2 Time Left",
        DevicePropertyCode::MediaSLOT3RemainingTime => "Slot 3 Time Left",
        DevicePropertyCode::MediaSLOT1FileType => "Slot 1 File Type",
        DevicePropertyCode::MediaSLOT2FileType => "Slot 2 File Type",
        DevicePropertyCode::MediaSLOT1ImageQuality => "Slot 1 Image Quality",
        DevicePropertyCode::MediaSLOT2ImageQuality => "Slot 2 Image Quality",
        DevicePropertyCode::MediaSLOT1QuickFormatEnableStatus => "Slot 1 Quick Format",
        DevicePropertyCode::MediaSLOT2QuickFormatEnableStatus => "Slot 2 Quick Format",
        DevicePropertyCode::AutoSwitchMedia => "Auto Switch Media",
        DevicePropertyCode::SimulRecSetting => "Simultaneous Recording",

        // === Power & Battery ===
        DevicePropertyCode::BatteryRemain => "Battery Remaining",
        DevicePropertyCode::BatteryLevel => "Battery Level",
        DevicePropertyCode::BatteryRemainingInMinutes => "Battery (Minutes)",
        DevicePropertyCode::BatteryRemainingInVoltage => "Battery Voltage",
        DevicePropertyCode::BatteryRemainDisplayUnit => "Battery Display Unit",
        DevicePropertyCode::PowerSource => "Power Source",
        DevicePropertyCode::AutoPowerOffTemperature => "Auto Power Off Temp",
        DevicePropertyCode::DeviceOverheatingState => "Overheating State",
        DevicePropertyCode::RecordablePowerSources => "Recordable Power Sources",
        DevicePropertyCode::USBPowerSupply => "USB Power Supply",
        DevicePropertyCode::DCVoltage => "DC Voltage",

        // === Zoom ===
        DevicePropertyCode::ZoomScale => "Zoom Scale",
        DevicePropertyCode::ZoomSetting => "Zoom Setting",
        DevicePropertyCode::ZoomOperation => "Zoom Operation",
        DevicePropertyCode::ZoomPositionSetting => "Zoom Position",
        DevicePropertyCode::ZoomPositionCurrentValue => "Zoom Position (Current)",
        DevicePropertyCode::ZoomDrivingStatus => "Zoom Status",
        DevicePropertyCode::ZoomSpeedRange => "Zoom Speed Range",
        DevicePropertyCode::ZoomDistance => "Zoom Distance",
        DevicePropertyCode::ZoomDistanceUnitSetting => "Zoom Distance Unit",
        DevicePropertyCode::DigitalZoomScale => "Digital Zoom Scale",
        DevicePropertyCode::DigitalExtenderMagnificationSetting => "Digital Extender",

        // === Lens ===
        DevicePropertyCode::LensModelName => "Lens Model",
        DevicePropertyCode::LensCompensationShading => "Lens Comp: Shading",
        DevicePropertyCode::LensCompensationChromaticAberration => "Lens Comp: Chromatic",
        DevicePropertyCode::LensCompensationDistortion => "Lens Comp: Distortion",
        DevicePropertyCode::LensCompensationBreathing => "Lens Comp: Breathing",
        DevicePropertyCode::FocalDistanceInMeter => "Focal Distance (m)",
        DevicePropertyCode::FocalDistanceInFeet => "Focal Distance (ft)",
        DevicePropertyCode::FocalDistanceUnitSetting => "Focal Distance Unit",

        // === Flash ===
        DevicePropertyCode::FlashMode => "Flash Mode",
        DevicePropertyCode::FlashCompensation => "Flash Compensation",
        DevicePropertyCode::WirelessFlash => "Wireless Flash",
        DevicePropertyCode::RedEyeReduction => "Red Eye Reduction",

        // === Audio ===
        DevicePropertyCode::AudioRecording => "Audio Recording",
        DevicePropertyCode::AudioSignals => "Audio Signals",
        DevicePropertyCode::AudioSignalsVolume => "Audio Volume",
        DevicePropertyCode::AudioLevelDisplay => "Audio Level Display",
        DevicePropertyCode::WindNoiseReduct => "Wind Noise Reduction",
        DevicePropertyCode::AudioInputCH1Level => "Audio CH1 Level",
        DevicePropertyCode::AudioInputCH2Level => "Audio CH2 Level",
        DevicePropertyCode::AudioInputCH3Level => "Audio CH3 Level",
        DevicePropertyCode::AudioInputCH4Level => "Audio CH4 Level",
        DevicePropertyCode::AudioInputMasterLevel => "Audio Master Level",

        // === Picture Profile ===
        DevicePropertyCode::PictureProfile => "Picture Profile",
        DevicePropertyCode::PictureProfileGamma => "PP Gamma",
        DevicePropertyCode::PictureProfileColorMode => "PP Color Mode",
        DevicePropertyCode::PictureProfileSaturation => "PP Saturation",
        DevicePropertyCode::PictureProfileBlackLevel => "PP Black Level",
        DevicePropertyCode::PictureProfileBlackGammaLevel => "PP Black Gamma",
        DevicePropertyCode::PictureProfileBlackGammaRange => "PP Black Gamma Range",
        DevicePropertyCode::PictureProfileKneeMode => "PP Knee Mode",
        DevicePropertyCode::PictureProfileDetailLevel => "PP Detail Level",
        DevicePropertyCode::CreativeLook => "Creative Look",
        DevicePropertyCode::CreativeLookContrast => "Creative Look: Contrast",
        DevicePropertyCode::CreativeLookHighlights => "Creative Look: Highlights",
        DevicePropertyCode::CreativeLookShadows => "Creative Look: Shadows",
        DevicePropertyCode::CreativeLookSaturation => "Creative Look: Saturation",
        DevicePropertyCode::CreativeLookSharpness => "Creative Look: Sharpness",
        DevicePropertyCode::CreativeLookSharpnessRange => "Creative Look: Sharpness Range",
        DevicePropertyCode::CreativeLookClarity => "Creative Look: Clarity",
        DevicePropertyCode::CreativeLookFade => "Creative Look: Fade",
        DevicePropertyCode::GammaDisplayAssist => "Gamma Display Assist",
        DevicePropertyCode::GammaDisplayAssistType => "Gamma Assist Type",

        // === ND Filter ===
        DevicePropertyCode::NDFilter => "ND Filter",
        DevicePropertyCode::NDFilterMode => "ND Filter Mode",
        DevicePropertyCode::NDFilterModeSetting => "ND Mode Setting",
        DevicePropertyCode::NDFilterValue => "ND Filter Value",
        DevicePropertyCode::NDFilterSwitchingSetting => "ND Switching",

        // === Display & Monitor ===
        DevicePropertyCode::LiveViewDisplayEffect => "Live View Display Effect",
        DevicePropertyCode::LiveViewStatus => "Live View Status",
        DevicePropertyCode::LiveViewImageQuality => "Live View Quality",
        DevicePropertyCode::LiveViewProtocol => "Live View Protocol",
        DevicePropertyCode::DispMode => "Display Mode",
        DevicePropertyCode::DispModeSetting => "Display Mode Setting",
        DevicePropertyCode::MonitorLUTSetting => "Monitor LUT",
        DevicePropertyCode::GridLineDisplay => "Grid Line Display",
        DevicePropertyCode::GridLineType => "Grid Line Type",
        DevicePropertyCode::MonitorBrightnessType => "Monitor Brightness",
        DevicePropertyCode::MonitorBrightnessManual => "Monitor Brightness (Manual)",
        DevicePropertyCode::SelectFinder => "Select Finder",
        DevicePropertyCode::DisplayQualityFinder => "Finder Display Quality",

        // === Stabilization ===
        DevicePropertyCode::ImageStabilizationSteadyShot => "SteadyShot",
        DevicePropertyCode::MovieImageStabilizationSteadyShot => "Movie SteadyShot",
        DevicePropertyCode::MovieImageStabilizationLevel => "SteadyShot Level",
        DevicePropertyCode::ImageStabilizationSteadyShotAdjust => "SteadyShot Adjust",
        DevicePropertyCode::ImageStabilizationSteadyShotFocalLength => "SteadyShot Focal Length",

        // === Silent Mode ===
        DevicePropertyCode::SilentMode => "Silent Mode",
        DevicePropertyCode::SilentModeApertureDriveInAF => "Silent: Aperture Drive",
        DevicePropertyCode::SilentModeShutterWhenPowerOff => "Silent: Shutter Power Off",
        DevicePropertyCode::SilentModeAutoPixelMapping => "Silent: Auto Pixel Mapping",

        // === Streaming ===
        DevicePropertyCode::StreamStatus => "Stream Status",
        DevicePropertyCode::StreamModeSetting => "Stream Mode",
        DevicePropertyCode::StreamDisplayName => "Stream Display Name",
        DevicePropertyCode::StreamLatency => "Stream Latency",

        // === Network & FTP ===
        DevicePropertyCode::FTPFunction => "FTP Function",
        DevicePropertyCode::FTPAutoTransfer => "FTP Auto Transfer",
        DevicePropertyCode::FTPConnectionStatus => "FTP Connection Status",
        DevicePropertyCode::WakeOnLAN => "Wake on LAN",
        DevicePropertyCode::IPSetupProtocolSetting => "IP Setup Protocol",

        // === Custom Buttons ===
        DevicePropertyCode::AssignableButton1 => "Assignable Button 1",
        DevicePropertyCode::AssignableButton2 => "Assignable Button 2",
        DevicePropertyCode::AssignableButton3 => "Assignable Button 3",
        DevicePropertyCode::AssignableButton4 => "Assignable Button 4",
        DevicePropertyCode::AssignableButton5 => "Assignable Button 5",
        DevicePropertyCode::LensAssignableButton1 => "Lens Assignable Button",
        DevicePropertyCode::FunctionOfTouchOperation => "Touch Function",
        DevicePropertyCode::TouchFunctionInMF => "Touch Function (MF)",

        // === System ===
        DevicePropertyCode::ModelName => "Camera Model",
        DevicePropertyCode::BodySerialNumber => "Serial Number",
        DevicePropertyCode::SoftwareVersion => "Firmware Version",
        DevicePropertyCode::DateTimeSettings => "Date/Time",
        DevicePropertyCode::LanguageSetting => "Language",
        DevicePropertyCode::CameraOperatingMode => "Operating Mode",
        DevicePropertyCode::CameraSettingSaveReadState => "Settings State",

        // === Default fallback ===
        // For any property not explicitly listed, use the SDK-provided name
        _ => code.name(),
    }
}
