//! Movie category: video recording and movie properties.

use super::{Category, PropertyDef, PropertyValueType};
use crsdk_sys::DevicePropertyCode;

use DevicePropertyCode as C;
use PropertyValueType as V;

pub struct Movie;

impl Category for Movie {
    const PROPERTIES: &'static [PropertyDef] = &[
        PropertyDef::new(
            C::MovieFileFormat,
            "Movie Format",
            "Video container format. XAVC S is H.264 in MP4. XAVC HS is H.265 (HEVC) for higher efficiency.",
            Some(V::MovieFileFormat),
        ),
        PropertyDef::new(
            C::MovieRecordingSetting,
            "Movie Setting",
            "Video resolution and quality settings combined. Higher settings require more storage.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieRecordingFrameRateSetting,
            "Movie FPS",
            "Recording frame rate. 24p for cinema look, 30p for broadcast, 60p for smooth motion, 120p for slow motion.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieRecordingResolutionForMain,
            "Main Resolution",
            "Main recording resolution (4K, 1080p, etc.).",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieRecordingResolutionForProxy,
            "Proxy Resolution",
            "Resolution for proxy files used in editing.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieRecordingFrameRateProxySetting,
            "Proxy FPS",
            "Frame rate for proxy recording.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieShootingMode,
            "Movie Mode",
            "Overall movie shooting mode configuration.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieShootingModeColorGamut,
            "Movie Gamut",
            "Color gamut for movie shooting.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieShootingModeTargetDisplay,
            "Target Display",
            "Target display type for movie shooting.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::RecorderControlProxySetting,
            "Proxy Control",
            "Proxy recorder control settings.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MoviePlayButton,
            "Play",
            "Play button for movie playback.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MoviePlayPauseButton,
            "Pause",
            "Play/pause toggle for movie playback.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MoviePlayStopButton,
            "Stop",
            "Stop button for movie playback.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieForwardButton,
            "Forward",
            "Fast forward button for movie playback.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieRewindButton,
            "Rewind",
            "Rewind button for movie playback.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieNextButton,
            "Next",
            "Skip to next clip during playback.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MoviePrevButton,
            "Previous",
            "Skip to previous clip during playback.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieRecReviewButton,
            "Rec Review",
            "Review recently recorded movie clip.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SQRecordingFrameRateSetting,
            "S&Q Rec FPS",
            "Slow & Quick mode recording frame rate.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SQFrameRate,
            "S&Q Frame Rate",
            "Slow & Quick playback frame rate.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SQRecordingSetting,
            "S&Q Setting",
            "Slow & Quick recording settings.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::AudioRecording,
            "Audio Rec",
            "Enable or disable audio recording with video.",
            Some(V::OnOff),
        ),
        PropertyDef::new(
            C::TimeCodePreset,
            "TC Preset",
            "Set the starting timecode value.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::TimeCodeFormat,
            "TC Format",
            "Timecode format (drop frame, non-drop frame).",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::TimeCodeRun,
            "TC Run",
            "Timecode run mode (free run, record run).",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::TimeCodeMake,
            "TC Make",
            "How timecode is generated (preset, regenerate).",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::UserBitTimeRec,
            "UB Time Rec",
            "User bit time recording mode.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieImageStabilizationSteadyShot,
            "Movie SteadyShot",
            "Image stabilization mode for movie recording.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieProxyFileFormat,
            "Proxy Format",
            "File format for proxy recordings.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::ProxyRecordingSetting,
            "Proxy Setting",
            "Proxy recording configuration.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieHDMIOutputRecMedia,
            "HDMI Rec Media",
            "HDMI output settings when recording.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieHDMIOutputResolution,
            "HDMI Resolution",
            "HDMI output resolution during recording.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieHDMIOutput4KSetting,
            "HDMI 4K",
            "4K HDMI output configuration.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieHDMIOutputRAW,
            "HDMI RAW",
            "RAW video output over HDMI.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieHDMIOutputRawSetting,
            "HDMI RAW Setting",
            "RAW HDMI output configuration.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieHDMIOutputColorGamutForRAWOut,
            "HDMI RAW Gamut",
            "Color gamut for RAW HDMI output.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieHDMIOutputTimeCode,
            "HDMI TC",
            "Embed timecode in HDMI output.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieHDMIOutputRecControl,
            "HDMI Rec Control",
            "Recording control via HDMI.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieHDMIOutputAudioCH,
            "HDMI Audio CH",
            "Audio channel configuration for HDMI output.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::RecorderStartMain,
            "Start Main Rec",
            "Start main recorder.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::RecorderClipName,
            "Clip Name",
            "Current clip name.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::RecorderControlMainSetting,
            "Main Rec Control",
            "Main recorder control settings.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::RecorderSaveDestination,
            "Save Destination",
            "Destination for recorded footage.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::RecorderMainStatus,
            "Main Rec Status",
            "Main recorder status.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::RecordingState,
            "Recording",
            "Current recording state.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::RecordingFolderFormat,
            "Folder Format",
            "Recording folder structure format.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::RecordingFileNumber,
            "File Number",
            "File numbering for recordings.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SQModeSetting,
            "S&Q Mode",
            "Slow & Quick mode configuration.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::LogShootingMode,
            "Log Mode",
            "Log gamma shooting mode for maximum dynamic range.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::VideoRecordingFormatQuality,
            "Rec Quality",
            "Video recording quality level.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::VideoRecordingFormatBitrateSetting,
            "Rec Bitrate",
            "Video recording bitrate configuration.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::ValidRecordingVideoFormat,
            "Valid Formats",
            "Valid video formats for current settings.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::VideoStreamMovieRecPermission,
            "Stream Rec",
            "Permission for video stream movie recording.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::TimeCodePresetResetEnableStatus,
            "TC Reset",
            "Whether timecode preset can be reset.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieIntervalRecIntervalTime,
            "Interval Time",
            "Time between shots in movie interval recording.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieIntervalRecFrameRateSetting,
            "Interval FPS",
            "Frame rate for movie interval recording.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieIntervalRecRecordingSetting,
            "Interval Setting",
            "Recording settings for movie interval mode.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieFTPAutoTransferTarget,
            "FTP Auto Target",
            "Target for automatic FTP transfer of movies.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieFTPTransferTarget,
            "FTP Target",
            "Target for manual FTP transfer of movies.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieImageStabilizationLevel,
            "Movie IS Level",
            "Image stabilization level for movie recording.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieQualityFullAutoMode,
            "Full Auto Quality",
            "Full auto quality mode for movie recording.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieRecordingResolutionForRTSP,
            "RTSP Resolution",
            "Recording resolution for RTSP streaming.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieRecordingResolutionForRAW,
            "RAW Resolution",
            "Recording resolution for RAW video.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieRecordingFrameRateRTSPSetting,
            "RTSP FPS",
            "Frame rate setting for RTSP recording.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PictureCacheRecSetting,
            "Cache Rec",
            "Picture cache recording mode configuration.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PictureCacheRecSizeAndTime,
            "Cache Size/Time",
            "Buffer size and time for picture cache recording.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieIntervalRecFrames,
            "Interval Frames",
            "Number of frames in movie interval recording.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieRecReviewPlayingState,
            "Review State",
            "Playback state during recording review.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MoviePlayingSpeed,
            "Play Speed",
            "Playback speed for movie review.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MoviePlayingState,
            "Play State",
            "Current movie playback state.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::RecorderStartProxy,
            "Start Proxy Rec",
            "Start proxy recorder.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::RecorderProxyStatus,
            "Proxy Status",
            "Proxy recorder status.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieRecButtonToggleEnableStatus,
            "Rec Btn Toggle",
            "Whether movie record button toggle is enabled.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieIntervalRecCountDownIntervalTime,
            "Interval Countdown",
            "Countdown interval for movie interval recording.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieIntervalRecRecordingDuration,
            "Interval Duration",
            "Duration of movie interval recording.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieRecordingMedia,
            "Rec Media",
            "Media destination for movie recording.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MovieRecordingFileNumber,
            "Movie File #",
            "File number for movie recordings.",
            Some(V::Integer),
        ),
    ];
}
