//! Other category: miscellaneous and uncategorized properties.
//!
//! This module serves as a catch-all for properties that don't fit neatly into
//! other semantic categories. Properties here may include:
//! - Camera system/status properties
//! - Network and connectivity features
//! - Interval shooting
//! - Subject recognition
//! - Various settings and controls

use super::{Category, PropertyCategory, PropertyDef, PropertyValueType};
use crsdk_sys::DevicePropertyCode;

use DevicePropertyCode as C;
use PropertyValueType as V;

/// Uncategorized properties.
pub struct Other;

impl Category for Other {
    const CATEGORY: PropertyCategory = PropertyCategory::Other;
    const NAME: &'static str = "Other";
    const PROPERTIES: &'static [PropertyDef] = &[
        PropertyDef::new(C::Undefined, "Unknown", "Undefined property.", None),
        PropertyDef::new(
            C::S1,
            "S1 (Half Press)",
            "Shutter half-press state. Activates metering and autofocus.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::S2,
            "S2 (Full Press)",
            "Shutter full-press state. Triggers image capture.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::AEL,
            "AE Lock",
            "Auto exposure lock. Holds current exposure settings.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FEL,
            "Flash EV Lock",
            "Flash exposure lock. Holds flash output level from pre-flash.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::RedEyeReduction,
            "Red-Eye",
            "Reduces red-eye effect in flash photos by pre-flash.",
            Some(V::OnOff),
        ),
        PropertyDef::new(
            C::DRO,
            "D-Range Optimizer",
            "Dynamic Range Optimizer. Automatically adjusts shadows and highlights.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::AspectRatio,
            "Aspect",
            "Image aspect ratio. 3:2 is standard, 16:9 for widescreen, 1:1 square.",
            Some(V::AspectRatio),
        ),
        PropertyDef::new(
            C::PriorityKeySettings,
            "Key Priority",
            "Which control takes priority when both photo and video controls are pressed.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::DateTimeSettings,
            "Date/Time",
            "Camera date, time, and timezone configuration.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::TouchOperation,
            "Touch Op",
            "Enable or disable touch screen functionality.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::BodyKeyLock,
            "Body Lock",
            "Lock camera body buttons to prevent accidental changes.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::BaseLookValue,
            "Base Look",
            "Base look profile value for color rendering.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FocalDistanceInMeter,
            "Focus Dist (m)",
            "Current focus distance displayed in meters.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FocalDistanceInFeet,
            "Focus Dist (ft)",
            "Current focus distance displayed in feet.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FocalDistanceUnitSetting,
            "Dist Unit",
            "Unit for displaying focus distance (meters or feet).",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::DepthOfFieldAdjustmentMode,
            "DOF Adj Mode",
            "Mode for adjusting depth of field preview.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::UserBitPreset,
            "User Bit",
            "User-defined bits embedded in timecode for identification.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SubjectRecognitionAF,
            "Subject Rec AF",
            "AI-powered subject detection for autofocus.",
            Some(V::SubjectRecognitionAF),
        ),
        PropertyDef::new(
            C::FunctionOfRemoteTouchOperation,
            "Remote Touch Func",
            "Function assigned to remote touch operation.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::RemoteTouchOperation,
            "Remote Touch",
            "Enable remote touch screen control.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::ExtendedInterfaceMode,
            "Ext Interface",
            "Extended interface mode for external devices.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FunctionOfTouchOperation,
            "Touch Func",
            "Function assigned to touch operations.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::DeleteUserBaseLook,
            "Del User Look",
            "Delete a user-created base look profile.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SelectUserBaseLookToEdit,
            "Edit User Look",
            "Select which user base look to edit.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SelectUserBaseLookToSetInPPLUT,
            "PP LUT Look",
            "Select user base look for picture profile LUT.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::UserBaseLookInput,
            "User Look Input",
            "Input settings for user base look creation.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::UserBaseLookAELevelOffset,
            "User Look AE Offs",
            "Exposure level offset for user base look.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FlickerLessShooting,
            "Flicker-Less",
            "Reduces banding from flickering artificial lights.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PlaybackVolumeSettings,
            "Playback Volume",
            "Volume level for playback audio.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::AutoReview,
            "Auto Image Review",
            "Shows captured image briefly after shooting.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::ModelName,
            "Camera Model",
            "Camera model identifier.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::BodySerialNumber,
            "Serial Number",
            "Unique camera serial number.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SoftwareVersion,
            "Firmware Version",
            "Current firmware version.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::IntervalRecMode,
            "Interval Rec",
            "Interval shooting mode for time-lapse photography.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::IntervalRecNumberOfShots,
            "Interval # Shots",
            "Total shots to capture during interval shooting.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::IntervalRecShootingInterval,
            "Interval Time",
            "Time between shots in interval shooting.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::IntervalRecShootingStartTime,
            "Interval Start",
            "Scheduled start time for interval shooting.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::IntervalRecStatus,
            "Interval Status",
            "Current status of interval shooting.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::IntervalRecShootIntervalPriority,
            "Interval Priority",
            "Priority setting for interval shooting timing.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::IntervalRecAETrackingSensitivity,
            "Interval AE Track",
            "AE tracking sensitivity during interval shooting.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::StreamModeSetting,
            "Stream Mode",
            "Configures the camera for live streaming output.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::StreamStatus,
            "Stream State",
            "Current streaming connection status.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::StreamDisplayName,
            "Stream Name",
            "Display name for the stream.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::StreamLatency,
            "Stream Delay",
            "Streaming latency setting (low vs quality).",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::StreamButtonEnableStatus,
            "Stream Btn Avail",
            "Whether stream button is enabled.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::StreamCipherType,
            "Stream Encrypt",
            "Encryption type for streaming.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::StreamSettingListOperationStatus,
            "Stream List Op",
            "Stream settings list operation status.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::StreamTTL,
            "Stream Time-To-Live",
            "Time-to-live for streaming packets.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::TargetStreamingDestinationSelect,
            "Stream Dest",
            "Select streaming destination.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::VideoStreamAdaptiveRateControl,
            "Stream ABR",
            "Adaptive bitrate control for streaming.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::VideoStreamBitRateCompressionMode,
            "Stream Comp Mode",
            "Bitrate compression mode for video stream.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::VideoStreamBitRateVBRMode,
            "Stream VBR",
            "Variable bitrate mode settings.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::VideoStreamCodec,
            "Stream Codec",
            "Video codec for streaming (H.264, H.265, etc.).",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::VideoStreamMaxBitRate,
            "Stream Max Bitrate",
            "Maximum bitrate for video streaming.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::VideoStreamResolution,
            "Stream Res",
            "Resolution for video streaming.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::VideoStreamResolutionMethod,
            "Stream Res Method",
            "Method for determining stream resolution.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::VideoStreamSelect,
            "Stream Select",
            "Select active video stream.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::VideoStreamSettingVersion,
            "Stream Ver",
            "Version of video stream settings.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FTPFunction,
            "FTP Enable",
            "Enables FTP file transfer functionality.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FTPAutoTransfer,
            "FTP Auto",
            "Automatically transfer files via FTP after capture.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FTPConnectionStatus,
            "FTP Status",
            "Current FTP connection status.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FTPConnectionErrorInfo,
            "FTP Error",
            "FTP connection error information.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FTPAutoTransferTarget,
            "FTP Auto Target",
            "Target files for FTP auto transfer.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FTPTransferTarget,
            "FTP Target",
            "Files selected for FTP transfer.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FTPServerSettingOperationEnableStatus,
            "FTP Server Avail",
            "FTP server settings operation availability.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FTPServerSettingVersion,
            "FTP Server Ver",
            "FTP server settings version.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FTPTransferSettingReadOperationEnableStatus,
            "FTP Read Avail",
            "FTP transfer read operation availability.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FTPTransferSettingSaveOperationEnableStatus,
            "FTP Save Avail",
            "FTP transfer save operation availability.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FTPTransferSettingSaveReadState,
            "FTP Save/Read",
            "FTP transfer settings save/read state.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FTPJobListDataVersion,
            "FTP Job Ver",
            "FTP job list data version.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SelectFTPServer,
            "FTP Server",
            "Select FTP server for transfer.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SelectFTPServerID,
            "FTP Server ID",
            "FTP server identifier.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::WakeOnLAN,
            "Wake on LAN",
            "Power on camera remotely via network signal.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SubjectRecognitionInAF,
            "Subj Rec in AF",
            "Subject recognition during autofocus.",
            Some(V::SubjectRecognitionAF),
        ),
        PropertyDef::new(
            C::SubjectRecognitionAnimalBirdPriority,
            "Animal/Bird Pri",
            "Priority between animal and bird detection.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SubjectRecognitionAnimalBirdDetectionParts,
            "A/B Det Parts",
            "Detection parts for animal/bird recognition.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SubjectRecognitionAnimalDetectionParts,
            "Animal Det Parts",
            "Body parts to detect for animals (eye, body).",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SubjectRecognitionAnimalDetectionSensitivity,
            "Animal Det Sens",
            "Sensitivity for animal detection.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SubjectRecognitionAnimalTrackingSensitivity,
            "Animal Track Sens",
            "Tracking sensitivity for animals.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SubjectRecognitionAnimalTrackingSubjectShiftRange,
            "Animal Shift Rng",
            "Range for animal subject shift tracking.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SubjectRecognitionBirdDetectionParts,
            "Bird Det Parts",
            "Body parts to detect for birds.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SubjectRecognitionBirdDetectionSensitivity,
            "Bird Det Sens",
            "Sensitivity for bird detection.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SubjectRecognitionBirdTrackingSensitivity,
            "Bird Track Sens",
            "Tracking sensitivity for birds.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SubjectRecognitionBirdTrackingSubjectShiftRange,
            "Bird Shift Range",
            "Range for bird subject shift tracking.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SubjectRecognitionInsectDetectionSensitivity,
            "Insect Det Sens",
            "Sensitivity for insect detection.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SubjectRecognitionInsectTrackingSensitivity,
            "Insect Track Sens",
            "Tracking sensitivity for insects.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SubjectRecognitionInsectTrackingSubjectShiftRange,
            "Insect Shift Rng",
            "Range for insect subject shift tracking.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SubjectRecognitionCarTrainDetectionSensitivity,
            "Car/Train Det Sns",
            "Sensitivity for car/train detection.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SubjectRecognitionCarTrainTrackingSensitivity,
            "Car/Train Trk Sns",
            "Tracking sensitivity for cars/trains.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SubjectRecognitionCarTrainTrackingSubjectShiftRange,
            "Car/Train Shift",
            "Range for car/train subject shift tracking.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SubjectRecognitionPlaneDetectionSensitivity,
            "Plane Det Sens",
            "Sensitivity for airplane detection.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SubjectRecognitionPlaneTrackingSensitivity,
            "Plane Track Sens",
            "Tracking sensitivity for airplanes.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SubjectRecognitionPlaneTrackingSubjectShiftRange,
            "Plane Shift Range",
            "Range for airplane subject shift tracking.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SubjectRecognitionPersonTrackingSubjectShiftRange,
            "Person Shift Rng",
            "Range for person subject shift tracking.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SubjectRecognitionPriorityOnRegisteredFace,
            "Registered Face",
            "Priority for registered face recognition.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::APSCOrFullSwitchingEnableStatus,
            "APS-C Switch Avail",
            "Whether APS-C/Full switching is available.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::APSCOrFullSwitchingSetting,
            "APS-C/Full",
            "APS-C or full-frame sensor mode setting.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::APSCS35,
            "APS-C/S35 Crop",
            "APS-C/Super 35mm crop mode.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::ContinuousShootingSpotBoostStatus,
            "Boost Status",
            "Continuous shooting spot boost status.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::ContinuousShootingSpotBoostFrameSpeed,
            "Boost Speed",
            "Frame speed for spot boost mode.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::ContinuousShootingSpotBoostEnableStatus,
            "Boost Avail",
            "Whether spot boost is available.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SoftSkinEffect,
            "Soft Skin",
            "Soft skin smoothing effect for portraits.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SimulRecSetting,
            "Simul Rec",
            "Simultaneous recording to multiple slots/formats.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::ColorSpace,
            "Color Gamut",
            "Color space for images (sRGB, AdobeRGB).",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::ReleaseWithoutCard,
            "No Card Release",
            "Allow shooting without memory card inserted.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::CameraOperatingMode,
            "Op Mode",
            "Current camera operating mode.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::CameraErrorCautionStatus,
            "Error Status",
            "Camera error and warning status.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::CameraSystemErrorInfo,
            "System Error",
            "Detailed camera system error information.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::CameraShakeStatus,
            "Shake Status",
            "Camera shake detection status.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::CameraSettingReadOperationEnableStatus,
            "Read Settings Avail",
            "Whether settings can be read.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::CameraSettingSaveOperationEnableStatus,
            "Save Settings Avail",
            "Whether settings can be saved.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::CameraSettingsResetEnableStatus,
            "Reset Avail",
            "Whether settings reset is available.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::CameraSettingSaveReadState,
            "Settings State",
            "Camera settings save/read state.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SdkControlMode,
            "SDK Control",
            "SDK control mode status.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SystemErrorCautionStatus,
            "Sys Error Status",
            "System-level error and warning status.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::UpdateBodyStatus,
            "Update Status",
            "Camera body update status.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::CinematicVlogSetting,
            "Cinematic Vlog",
            "Cinematic vlog mode configuration.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::CinematicVlogLook,
            "Vlog Look",
            "Visual look preset for cinematic vlog.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::CinematicVlogMood,
            "Vlog Mood",
            "Mood setting for cinematic vlog.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::CinematicVlogAFTransitionSpeed,
            "Vlog AF Speed",
            "AF transition speed in cinematic vlog mode.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::ContentsTransferStatus,
            "Transfer Status",
            "File transfer status.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::ContentsTransferProgress,
            "Transfer Progress",
            "File transfer progress percentage.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::ContentsTransferCancelEnableStatus,
            "Cancel Transfer",
            "Whether transfer can be cancelled.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::DepthOfFieldAdjustmentInterlockingMode,
            "DOF Interlock",
            "DOF adjustment interlocking mode.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::DifferentSetForSQMovie,
            "S&Q Diff Set",
            "Different settings for S&Q movie mode.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::EframingAutoFraming,
            "E-Frame Auto",
            "Auto framing for electronic framing.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::EframingModeAuto,
            "E-Frame Mode Auto",
            "Auto mode for electronic framing.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::EframingProductionEffect,
            "E-Frame Effect",
            "Production effect for e-framing.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::EframingHDMICrop,
            "E-Frame HDMI Crop",
            "HDMI output crop for e-framing.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::EframingRecordingImageCrop,
            "E-Frame Rec Crop",
            "Recording image crop for e-framing.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::EframingScaleAuto,
            "E-Frame Scale",
            "Auto scale for electronic framing.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::EframingSpeedAuto,
            "E-Frame Spd Auto",
            "Auto speed for electronic framing.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::EframingSpeedPTZ,
            "E-Frame PTZ Spd",
            "PTZ speed for electronic framing.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::EframingTrackingStartMode,
            "E-Frame Track",
            "Tracking start mode for e-framing.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::EframingType,
            "E-Frame Type",
            "Type of electronic framing.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::EframingCommandVersion,
            "E-Frame Ver",
            "E-framing command version.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::EstimatePictureSize,
            "Est File Size",
            "Estimated file size for current settings.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::AreaTimeZoneSettingVersion,
            "Time Zone Ver",
            "Time zone settings version.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::CallSetting,
            "Call Config",
            "Communication call settings.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::AutoRecognitionTargetCandidates,
            "Auto Rec Targets",
            "Available auto recognition targets.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::AutoRecognitionTargetSetting,
            "Auto Rec Target",
            "Auto recognition target configuration.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::CameraEframing,
            "Cam E-Frame",
            "Camera electronic framing setting.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::CameraLeverFunction,
            "Lever Function",
            "Function assigned to camera lever.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::ControlForHDMI,
            "HDMI Control",
            "HDMI-CEC control settings.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::DebugMode,
            "Debug Enable",
            "Debug mode for development.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::CancelRemoteTouchOperationEnableStatus,
            "Cancel Touch Avail",
            "Whether remote touch cancel is available.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FlickerLessShootingStatus,
            "Flicker-Less Stat",
            "Flicker-less shooting operation status.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FlickerScanEnableStatus,
            "Flicker Scan Avail",
            "Whether flicker scan is available.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FlickerScanStatus,
            "Flicker Scan Stat",
            "Flicker scan operation status.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FullTimeDMF,
            "Full-Time DMF",
            "Full-time direct manual focus override.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::GetOnly,
            "Read-Only Prop",
            "Read-only property indicator.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::WindNoiseReduct,
            "Wind Noise Red",
            "Wind noise reduction for built-in microphone.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::DigitalExtenderMagnificationSetting,
            "Digital Extender",
            "Digital extender magnification level.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MeteredManualLevel,
            "Meter Level (M)",
            "Exposure meter reading in manual mode.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PaintLookAutoKnee,
            "PL Auto Knee",
            "Auto knee setting for paint look.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PaintLookBBlack,
            "PL B Black",
            "Blue black level for paint look.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PaintLookRBlack,
            "PL R Black",
            "Red black level for paint look.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PaintLookMasterBlack,
            "PL Master Black",
            "Master black level for paint look.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PaintLookDetailLevel,
            "PL Detail Level",
            "Detail level for paint look.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PaintLookDetailSetting,
            "PL Detail",
            "Detail settings for paint look.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PaintLookKneePoint,
            "PL Knee Point",
            "Knee point for paint look.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PaintLookKneeSetting,
            "PL Knee",
            "Knee settings for paint look.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PaintLookKneeSlope,
            "PL Knee Slope",
            "Knee slope for paint look.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PaintLookMultiMatrixAreaIndication,
            "PL MM Area",
            "Multi-matrix area indication.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PaintLookMultiMatrixAxis,
            "PL MM Axis",
            "Multi-matrix axis selection.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PaintLookMultiMatrixHue,
            "PL MM Hue",
            "Multi-matrix hue adjustment.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PaintLookMultiMatrixSaturation,
            "PL MM Sat",
            "Multi-matrix saturation adjustment.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PaintLookMultiMatrixSetting,
            "PL MM Setting",
            "Multi-matrix configuration.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PaintLookUserMatrixBG,
            "PL UM B-G",
            "User matrix blue-green adjustment.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PaintLookUserMatrixBR,
            "PL UM B-R",
            "User matrix blue-red adjustment.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PaintLookUserMatrixGB,
            "PL UM G-B",
            "User matrix green-blue adjustment.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PaintLookUserMatrixGR,
            "PL UM G-R",
            "User matrix green-red adjustment.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PaintLookUserMatrixRB,
            "PL UM R-B",
            "User matrix red-blue adjustment.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PaintLookUserMatrixRG,
            "PL UM R-G",
            "User matrix red-green adjustment.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PaintLookUserMatrixLevel,
            "PL UM Level",
            "User matrix overall level.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PaintLookUserMatrixPhase,
            "PL UM Phase",
            "User matrix phase adjustment.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PaintLookUserMatrixSetting,
            "PL UM Setting",
            "User matrix configuration.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PanLimitMode,
            "Pan Limit Enable",
            "Pan movement limit mode.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PanLimitRangeMaximum,
            "Pan Max",
            "Maximum pan angle limit.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PanLimitRangeMinimum,
            "Pan Min",
            "Minimum pan angle limit.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PanPositionCurrentValue,
            "Pan Position",
            "Current pan position value.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PanPositionStatus,
            "Pan Status",
            "Pan position status.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PanTiltAccelerationRampCurve,
            "Pan/Tilt Accel",
            "Pan/tilt acceleration curve.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::TiltLimitMode,
            "Tilt Limit Enable",
            "Tilt movement limit mode.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::TiltLimitRangeMaximum,
            "Tilt Max",
            "Maximum tilt angle limit.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::TiltLimitRangeMinimum,
            "Tilt Min",
            "Minimum tilt angle limit.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::TiltPositionCurrentValue,
            "Tilt Position",
            "Current tilt position value.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::TiltPositionStatus,
            "Tilt Status",
            "Tilt position status.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MonitoringAvailableFormat,
            "Mon Avail Format",
            "Available monitoring output formats.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MonitoringDeliveringStatus,
            "Mon Deliver Status",
            "Monitoring delivery status.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MonitoringDeliveryTypeSupportInfo,
            "Mon Delivery Info",
            "Supported monitoring delivery types.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MonitoringFormatSupportInformation,
            "Mon Format Info",
            "Monitoring format support info.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MonitoringIsDelivering,
            "Mon Is Delivering",
            "Whether monitoring is actively delivering.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MonitoringOutputFormat,
            "Mon Output",
            "Current monitoring output format.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MonitoringSettingVersion,
            "Mon Ver",
            "Monitoring settings version.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MonitoringTransportProtocol,
            "Mon Protocol",
            "Monitoring transport protocol.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::TallyLampControlGreen,
            "Tally Green",
            "Green tally lamp control.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::TallyLampControlRed,
            "Tally Red",
            "Red tally lamp control.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::TallyLampControlYellow,
            "Tally Yellow",
            "Yellow tally lamp control.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::UserBitPresetResetEnableStatus,
            "UB Reset Avail",
            "User bit preset reset availability.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::UserBaseLookOutput,
            "User Look Output",
            "User base look output setting.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::TimeShiftPreShootingTimeSetting,
            "Time Shift Pre",
            "Pre-shooting time for time shift mode.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::TimeShiftShooting,
            "Time Shift",
            "Time shift shooting mode.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::TimeShiftShootingStatus,
            "Time Shift Status",
            "Time shift shooting status.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::TimeShiftTriggerSetting,
            "Time Shift Trigger",
            "Trigger setting for time shift mode.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PlaySetOfMultiMedia,
            "Play Multi-Media",
            "Multi-media playback set selection.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PlaybackContentsName,
            "PB Content Name",
            "Name of current playback content.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PlaybackContentsNumber,
            "PB Content #",
            "Number of current playback content.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PlaybackContentsRecordingDateTime,
            "PB Date/Time",
            "Recording date/time of playback content.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PlaybackContentsRecordingFileFormat,
            "PB Format",
            "File format of playback content.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PlaybackContentsRecordingFrameRate,
            "PB Frame Rate",
            "Frame rate of playback content.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PlaybackContentsRecordingResolution,
            "PB Resolution",
            "Resolution of playback content.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PlaybackContentsTotalNumber,
            "PB Total #",
            "Total number of playback contents.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PlaybackViewMode,
            "PB View Mode",
            "Playback view mode.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::BaseLookAppliedofPlayback,
            "PB Look Applied",
            "Base look applied during playback.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::BaseLookNameofPlayback,
            "PB Look Name",
            "Name of base look for playback.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::BaseLookImportOperationEnableStatus,
            "Look Import Avail",
            "Base look import availability.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::TeleWideLeverValueCapability,
            "Tele/Wide Cap",
            "Tele/wide lever value capability.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::CameraButtonFunction,
            "Cam Btn Func",
            "Function assigned to camera button.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::CameraButtonFunctionMulti,
            "Cam Btn Multi",
            "Multiple functions for camera button.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::CameraButtonFunctionStatus,
            "Cam Btn Status",
            "Camera button function status.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::CameraDialFunction,
            "Cam Dial Func",
            "Function assigned to camera dial.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::RemoteKeyThumbnailButton,
            "Remote Thumb Btn",
            "Thumbnail button on remote.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::RemoteKeySLOTSelectButton,
            "Remote Slot Btn",
            "Slot select button on remote.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::TouchFunctionInMF,
            "Touch in MF",
            "Touch function during manual focus.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::HomeMenuSetting,
            "Home Menu",
            "Home menu configuration.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::IRRemoteSetting,
            "IR Remote",
            "Infrared remote control settings.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::IPSetupProtocolSetting,
            "IP Protocol",
            "IP setup protocol configuration.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::LanguageSetting,
            "Language",
            "Camera menu language setting.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MaxVal,
            "Max Value Marker",
            "Maximum value indicator.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MaximumNumberOfBytes,
            "Max Bytes",
            "Maximum byte count.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::MicrophoneDirectivity,
            "Mic Pattern",
            "Microphone pickup pattern.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PixelMappingEnableStatus,
            "Pixel Map Avail",
            "Pixel mapping availability.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PostViewTransferResourceStatus,
            "Post-View Status",
            "Post-view transfer resource status.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PreAF,
            "Pre-AF",
            "Pre-AF (predictive autofocus) setting.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PresetPTZFSlotNumber,
            "PTZ Preset Slot",
            "PTZ preset slot number.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::ProductShowcaseSet,
            "Product Showcase",
            "Product showcase mode setting.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::ProgramShiftStatus,
            "P Shift Status",
            "Program shift mode status.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PushAFModeSetting,
            "Push AF Mode",
            "Push AF mode configuration.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::PushAGC,
            "Push Auto Gain",
            "Push auto gain control.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::RecognitionTarget,
            "Recog Target",
            "Current recognition target type.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::RemoteTouchOperationEnableStatus,
            "Remote Touch Avail",
            "Remote touch operation availability.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::RightLeftEyeSelect,
            "L/R Eye Select",
            "Eye selection for eye AF (left/right).",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SensorCleaningEnableStatus,
            "Sensor Clean Avail",
            "Sensor cleaning availability.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SetCopyright,
            "Copyright",
            "Copyright information to embed.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SetPhotographer,
            "Photographer",
            "Photographer name to embed.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SetPresetPTZFBinaryVersion,
            "PTZ Bin Ver",
            "PTZ preset binary version.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::ShootingEnableSettingLicense,
            "Shoot License",
            "Shooting license settings.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::ShootingTimingPreNotificationMode,
            "Shoot Pre-Notify",
            "Pre-notification mode for shooting timing.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SimulRecSettingMovieRecButton,
            "Simul Rec Btn",
            "Simultaneous recording button setting.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SnapshotInfo,
            "Snapshot Data",
            "Snapshot information.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SynchroterminalForcedOutput,
            "Sync Term Output",
            "Sync terminal forced output.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::TNumber,
            "T-Number",
            "T-number (transmission-adjusted f-number).",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::TopOfTheGroupShootingMarkSetting,
            "Group Mark",
            "Group shooting mark setting.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::TrackingOnAndAFOnEnableStatus,
            "Track/AF On Avail",
            "Tracking and AF enable status.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::UploadDatasetVersion,
            "Upload Dataset Ver",
            "Upload dataset version.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::WriteCopyrightInfo,
            "Write Copyright",
            "Write copyright info to images.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::SelectIPTCMetadata,
            "IPTC Metadata",
            "IPTC metadata selection.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FaceEyeFrameDisplay,
            "Face/Eye Frame",
            "Face/eye detection frame display.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FaceEyeDetectionAFStatus,
            "Face/Eye AF Status",
            "Face/eye detection AF status.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::AmountOfDefocusSetting,
            "Defocus Amount",
            "Amount of defocus for focus shift.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::FirmwareUpdateCommandVersion,
            "FW Update Ver",
            "Firmware update command version.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::CreateNewFolder,
            "Create Folder",
            "Create new folder on media.",
            Some(V::Integer),
        ),
        PropertyDef::new(
            C::CreateNewFolderEnableStatus,
            "Create Folder Avail",
            "Whether folder creation is available.",
            Some(V::Integer),
        ),
    ];
}

crate::register_category!(Other);
